# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
#  - name: Projects
#    url: '#projects'
#    weight: 30
  - name: Teaching
    url: '#teaching'
    weight: 45
  - name: Software
    url: '#software'
    weight: 50
  - name: Talks
    url: '#talks'
    weight: 55
  - name: Blog
    url: '#posts'
    weight: 56
  - name: Video
    url: 'video'
    weight: 57
#  - name: Publications
#    url: '#featured'
#    weight: 50
  - name: CV
    url: pdf/cv_pauldickman.pdf
    weight: 59
  - name: Contact
    url: '#contact'
    weight: 60
